"""Markdown report generation."""

from datetime import datetime
from typing import List, Optional

from ..passes.base import PassResult, Severity
from ..config import EdwordConfig
from ..discovery import BookInfo


def generate_report(
    results: List[PassResult],
    config: Optional[EdwordConfig] = None,
    book: Optional[BookInfo] = None,
) -> str:
    """
    Generate a markdown report from analysis results.

    Args:
        results: List of PassResult objects
        config: Edword configuration
        book: Book that was analyzed

    Returns:
        Markdown formatted report
    """
    lines = []

    # Header
    project_name = config.project_name if config else "Unknown Project"
    book_name = book.name if book else "Unknown Book"
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    lines.append(f"# Edword Analysis Report")
    lines.append("")
    lines.append(f"**Project:** {project_name}")
    lines.append(f"**Book:** {book_name}")
    lines.append(f"**Generated:** {timestamp}")
    lines.append("")

    # Summary
    total_errors = sum(len(r.errors) for r in results if r.success)
    total_warnings = sum(len(r.warnings) for r in results if r.success)
    total_info = sum(len(r.infos) for r in results if r.success)
    failed_passes = [r for r in results if not r.success]

    lines.append("## Summary")
    lines.append("")
    lines.append(f"- **Errors:** {total_errors}")
    lines.append(f"- **Warnings:** {total_warnings}")
    lines.append(f"- **Info:** {total_info}")
    if failed_passes:
        lines.append(f"- **Failed passes:** {len(failed_passes)}")
    lines.append("")

    # Results by pass
    lines.append("## Findings")
    lines.append("")

    for result in results:
        lines.append(f"### {result.pass_name}")
        lines.append("")

        if result.error:
            lines.append(f"> **Error:** {result.error}")
            lines.append("")
            continue

        if not result.findings:
            lines.append("*No issues found.*")
            lines.append("")
            continue

        # Group by severity
        for severity in [Severity.ERROR, Severity.WARNING, Severity.INFO]:
            findings = [f for f in result.findings if f.severity == severity]
            if not findings:
                continue

            severity_icon = {
                Severity.ERROR: "❌",
                Severity.WARNING: "⚠️",
                Severity.INFO: "ℹ️",
            }[severity]

            for finding in findings:
                lines.append(f"{severity_icon} **{finding.message}**")
                if finding.location:
                    lines.append(f"   - Location: {finding.location}")
                if finding.context:
                    # Format context as blockquote
                    ctx = finding.context[:300] + "..." if len(finding.context) > 300 else finding.context
                    lines.append(f"   > {ctx}")
                if finding.suggestion:
                    lines.append(f"   - **Fix:** {finding.suggestion}")
                lines.append("")

        # Stats if available
        if result.stats:
            lines.append(f"*Analysis stats: {result.stats}*")
            lines.append("")

    # Footer
    lines.append("---")
    lines.append("")
    lines.append("*Generated by [edword](https://github.com/dremy/edword)*")

    return "\n".join(lines)
